#!/bin/sh
#
# master branchへのコミットをできなくする

get_git_branch_name()
{
    branch="$(git symbolic-ref HEAD 2>/dev/null)" || "$(git describe --contains --all HEAD)"
    echo ${branch##refs/heads/}
}

is_on_master_branch()
{
    if [ "$(get_git_branch_name)" = "master" ]; then
        return 0
    fi
    return 1
}

is_on_master_branch

if [ $? -eq 0 ]; then
    echo "can't commit on master branch."
    echo "please commit on topic branch."
    exit 1
fi
